import 'package:flutter/material.dart';
import 'package:iconify_sdk/iconify_sdk.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return IconifyApp(
      // Configure the SDK to use compressed assets generated by the CLI.
      config: const IconifyConfig(
        compress: true,
        mode: IconifyMode.auto,
      ),
      child: MaterialApp(
        title: 'Iconify SDK Phase C/D Example',
        theme: ThemeData(
          colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
          useMaterial3: true,
        ),
        home: const MyHomePage(),
      ),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Iconify SDK Performance'),
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        actions: [
          IconButton(
            icon: const Icon(Icons.refresh),
            onPressed: () => setState(() {
              IconifyDiagnostics.reset();
            }),
          ),
        ],
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const _SectionTitle('1. Smart Rendering'),
            const Text(
              'The SDK automatically selects the best provider based on platform '
              'and availability. Here icons are being served from the GZIP-compressed '
              'Living Cache (used_icons.json.gz) or the Icon Font.',
            ),
            const SizedBox(height: 16),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceAround,
              children: [
                _IconColumn('mdi:home', 'MDI Home'),
                _IconColumn('lucide:zap', 'Lucide Flash'),
                _IconColumn('fa6-solid:ghost', 'FA6 Ghost'),
              ],
            ),
            const Divider(height: 48),
            const _SectionTitle('2. Native Icon Rendering'),
            const Text(
              'Monochrome icons can be rendered as native Flutter Icons using the '
              'generated .otf font, reducing bundle size by up to 40% vs SVG.',
            ),
            const SizedBox(height: 16),
            Center(
              child: IconifyIcon(
                'mdi:check-decagram',
                size: 64,
                color: Colors.green,
              ),
            ),
            const Divider(height: 48),
            const _SectionTitle('3. Diagnostics'),
            const Text(
              'Real-time stats from the IconifyPictureCache (Phase C.2).',
            ),
            const SizedBox(height: 16),
            const _DiagnosticsPanel(),
          ],
        ),
      ),
    );
  }
}

class _SectionTitle extends StatelessWidget {
  const _SectionTitle(this.title);
  final String title;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8),
      child: Text(
        title,
        style: Theme.of(context).textTheme.titleLarge?.copyWith(
              fontWeight: FontWeight.bold,
              color: Theme.of(context).colorScheme.primary,
            ),
      ),
    );
  }
}

class _IconColumn extends StatelessWidget {
  const _IconColumn(this.name, this.label);
  final String name;
  final String label;

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        IconifyIcon(name, size: 40),
        const SizedBox(height: 8),
        Text(label, style: Theme.of(context).textTheme.bodySmall),
      ],
    );
  }
}

class _DiagnosticsPanel extends StatefulWidget {
  const _DiagnosticsPanel();

  @override
  State<_DiagnosticsPanel> createState() => _DiagnosticsPanelState();
}

class _DiagnosticsPanelState extends State<_DiagnosticsPanel> {
  @override
  Widget build(BuildContext context) {
    final stats = IconifyDiagnostics.pictureCacheStats;

    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          children: [
            _StatRow('Cache Size', '${stats.length} / ${stats.maxEntries}'),
            _StatRow('Hits', '${stats.hits}'),
            _StatRow('Misses', '${stats.misses}'),
            _StatRow('Hit Rate', '${(stats.hitRate * 100).toStringAsFixed(1)}%'),
            const Divider(),
            const Text(
              'Hint: Scroll or interact to see cache hits increase.',
              style: TextStyle(fontStyle: FontStyle.italic, fontSize: 12),
            ),
          ],
        ),
      ),
    );
  }
}

class _StatRow extends StatelessWidget {
  const _StatRow(this.label, this.value);
  final String label;
  final String value;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 4),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text(label, style: const TextStyle(fontWeight: FontWeight.w500)),
          Text(value, style: const TextStyle(fontFamily: 'monospace')),
        ],
      ),
    );
  }
}
