name: bundled_example
description: A bundled example of using iconify_sdk.
publish_to: 'none'
version: 0.2.0

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  iconify_sdk:
    path: ../../packages/sdk
  # iconify_sdk_core is needed by the generated lib/icons.g.dart
  iconify_sdk_core:
    path: ../../packages/core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/iconify/used_icons.json.gz
    - assets/iconify/mdi.iconbin.gz
    - assets/iconify/lucide.iconbin.gz
    - assets/iconify/icons.sprite.svg.gz
    - assets/iconify/icons.sprite.json.gz
    - assets/iconify/icons.font.json.gz
    - assets/iconify/icons.font.otf.gz
