name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

  analyze:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [stable, beta]
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.sdk }}
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze project
        run: flutter analyze --fatal-infos --fatal-warnings

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [stable, beta]
    steps:
      - uses: actions/checkout@v4
      # We use flutter-action because iconify_sdk depends on Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.sdk }}
      - name: Install dependencies
        run: flutter pub get
      - name: Run tests
        run: flutter test