name: Publish (Dry Run)

on:
  push:
    branches:
      - 'release/*'

jobs:
  publish_dry_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      
      - name: Install Dependencies
        run: flutter pub get

      - name: Install Melos
        run: dart pub global activate melos

      - name: Publish Dry Run (All Packages)
        run: melos exec -- "dart pub publish --dry-run"